### ISSUE TITLE
DSL View type creation

### ISSUE THREAD

**Issue by iwarapter** [ghale/gradle-jenkins-plugin#44]
Can build pipeline views only be define by external dsl files when called like this:

```
apply plugin: 'com.terrafolio.jenkins'

jenkins {
    servers {
        testing {
            url 'http://localhost:8081'
            secure false
        }
    }

    defaultServer servers.testing // required

    dsl {
        job {
            name "job1"
        }
    }

    def dslFile = project.file('view.dsl')

    views {
        "project-A" {
            dsl dslFile
        }
    }
}
```

i have been unable to create a build pipeline view directly through the dsl in the build.gradle file.

I'm hoping im just doing something silly :)

**Comment by aeells** [comment]
:+1: for that. @ghale it would be good to reference this explicitly in the docs maybe - took me a while to work this one out... 

loving the project however, best approach i've found out there for templating your CI pipeline. thanks :)
