### ISSUE TITLE
PLugin no longer seems to be compatible with JDK 1.7

### ISSUE THREAD

**Issue by ysb33r** [ghale/gradle-jenkins-plugin#52]
I am getting `Unsupported major.minor version 51.0` as from `1.1.0` -> `1.2.3`.  with JDK 1.7.0_51.

I have checked `build.gradle` and it does have a sourceCompability or targetCompatibility set. It might be useful to set it to 1.7.

**Comment by ghale** [comment]
Thanks for reporting, I'll take a look.  I need to do some various housekeeping with this plugin anyways, so I'll try to carve out some time to do it in the next few days.

**Comment by ghale** [comment]
This is in v1.3.0.
