### ISSUE TITLE
Use newest job-dsl-plugin

### ISSUE THREAD

**Issue by sbergandy** [ghale/gradle-jenkins-plugin#54]
Is it possible to create a new release which will use the newest version 1.30 of job-dsl-plugin? Currently 1.25 is used. It is importnat because of this fix https://github.com/jenkinsci/job-dsl-plugin/pull/312

Without it it is not possible for example to create views like this:

```groovy
"view_name" {
  dsl {
    jobs {
      regex "some regex"
    }
  }
}
```

In order to do it the version 1.12 of gradle must be used where 2.3 is already there.

**Comment by jshickey** [comment]
Second this request, thanks.

**Comment by jhumphreys-scripps** [comment]
+1

**Comment by ghale** [comment]
Updated to job-dsl-core 1.34 with v1.3.0

**Comment by sbergandy** [comment]
Thx :+1:

**Comment by sbergandy** [comment]
I've tested it and works great.
