### ISSUE TITLE
Update Job DSL dependency to 1.35

### ISSUE THREAD

**Issue by Moritz90** [ghale/gradle-jenkins-plugin#62]
1.35 finally added support for the Join plugin (among others).

**Comment by kutzi** [comment]
1.36 added suppport for the Active choices plugin - which would be nice

**Comment by PeWolf** [comment]
1.39 added support for credentials in listTagsParam(String parameterName, String scmUrl) {...}
(https://jenkinsci.github.io/job-dsl-plugin/#path/job-parameters-listTagsParam).
I need this in my project!

**Comment by sschuberth** [comment]
The Job DSL dependency was recently [updated to 1.42](https://github.com/ghale/gradle-jenkins-plugin/pull/68), and the [update to 1.43](https://github.com/ghale/gradle-jenkins-plugin/pull/73) is pending review, so I think @Moritz90 can close this issue.
