### ISSUE TITLE
Releases 1.3.x not available at central repo

### ISSUE THREAD

**Issue by tschulte** [ghale/gradle-jenkins-plugin#72]
The releases 1.3.x are not available at https://plugins.gradle.org/m2/. Only the releases up to 1.2.3 are available. Yesterday 1.3.2 was available, but somehow it is gone. This might be an issue with bintray.

**Comment by rizvfe00** [comment]
1.3x versions are there now but 1.4x versions are not on bintray.  You can add the repository  job-core-dsl (the missing dependency) publishes to.

```
buildscript {
  repositories {
    maven { url 'http://maven.jenkins-ci.org:8081/content/repositories/releases' }
  }
}
```

**Comment by tschulte** [comment]
https://jcenter.bintray.com/com/terrafolio/gradle-jenkins-plugin/ still only contains the versions up to 1.2.3.

The repository http://maven.jenkins-ci.org:8081/content/repositories/releases seems not reachable.

**Comment by tschulte** [comment]
The problem is the following (see https://groups.google.com/forum/#!msg/sonarqube/AmJsTCycWvM/dfyyIJQyEgAJ)

https://plugins.gradle.org/m2/ does redirect to multiple other repositories (at their discretion). We are using Nexus as proxy, and we had to "disable repository checking".

I thought, https://plugins.gradle.org/m2 would only redirect to jcenter, since https://plugins.gradle.org/m2/com/terrafolio/gradle-jenkins-plugin/ redirects to jcenter, not listing versions 1.3.x, but https://plugins.gradle.org/m2/com/terrafolio/gradle-jenkins-plugin/1.3.2/gradle-jenkins-plugin-1.3.2.jar works.
