### ISSUE TITLE
Is this plugin still maintained?

### ISSUE THREAD

**Issue by crc83** [ghale/gradle-jenkins-plugin#87]
Is this plugin still maintained?

**Comment by crc83** [comment]
I will maintain it for a while here
https://github.com/crc83/gradle-jenkins-plugin
You may find this plugin here
https://plugins.gradle.org/plugin/com.sbelei.jenkins

**Comment by ghale** [comment]
@crc83 Sorry for the late response.  Thanks for doing some maintenance!

I find that I no longer have the time (and to some degree, the motivation, given that I don't use Jenkins in my day to day job anymore) to maintain this project in the way that it deserves.  I'd be very interested in having someone else take it over.  If you're interested, let me know!

Either way, thanks for giving it some love!

**Comment by dcendents** [comment]
@crc83 you should enable issues on your fork. I'm using your updated plugin v1.4.3 and it works great, I can now set CSRF protection. But I cannot update past that version, it always add a "null" in the string when trying to update projects.

i.e.: 
```
09:53:18.632 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: POST /nullcreateItem?name=my-project HTTP/1.1
09:53:18.635 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.1 404 Not Found
```

I'm not using folders and my jobs are name as usual, but I suspect your modifications for v1.4.4 to support folders breaks it for "normal" jobs.

**Comment by crc83** [comment]
Daniel,

I've enabled issues. Now you may post problem in my repo.
I'll try to do a fix today or tommorrow.

Thank you
-Serhi


2018-01-23 17:00 GMT+02:00 Daniel Beland <notifications@github.com>:

**Comment by crc83** [comment]
I applied fix and verified it. Please use latest 1.4.7 version

**Comment by dcendents** [comment]
Thanks @crc83  for your quick update, I'll test it on Monday at work and let you know.

**Comment by dcendents** [comment]
@crc83 version 1.4.7 works perfectly, thanks a lot.
If I have any other issue I'll open them directly with your fork.

regards,
