### ISSUE TITLE
1.3.4 is not available on the Gradle repo

### ISSUE THREAD

**Issue by foeser** [ghale/gradle-jenkins-plugin#88]
Hey @www44 ,

thanks for doing the latest release but I can't get it from Gradle repo:

`> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find com.terrafolio:gradle-jenkins-plugin:1.3.4.
     Searched in the following locations:
         https://plugins.gradle.org/m2/com/terrafolio/gradle-jenkins-plugin/1.3.4/gradle-jenkins-plugin-1.3.4.pom
`

It's listed but you can't download it. I also tried this one https://plugins.gradle.org/plugin/com.terrafolio.jenkins.www/1.3.4 without any success. 

It would be great if you could verify that! :)

Thanks,
Florian

**Comment by ghale** [comment]
Thanks for the reporting this @foeser - I can confirm I'm seeing the same problem.  I'll see if I can find out what's going on...

**Comment by www44** [comment]
Hi guys,

i've found the reason of our problems:
there was a bug in gradle publishing plugin (0.9.3) - files were not
uploaded to cloud automatically.
i'll prepare changes and publish new version.

BR,
Vladimir

2018-02-22 18:16 GMT+01:00 Gary Hale <notifications@github.com>:

**Comment by foeser** [comment]
Thanks!
